version: "3.8"
services:
  admin_api:
    container_name: django_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - admin_db
    environment:
      TZ: "Asia/Singapore"

  admin_db:
    container_name: django_admin_db
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "2021reactdrf"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Singapore"
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33066:3306"
